### PR TITLE
Upsert

### PR DESCRIPTION
**Pull request by jrmidkiff**
1. `databridge-etl-tools` reorganized into more cohesive and flexible style with sub-modules 
    1. `click` made more logical, and options and help improved
    2. README updated significantly
3. `Postgres` 
    1. now has `upsert_csv()` and `upsert_table()` methods 
    3. `Postgres` reorganized to be a context manager
        1. Enter method does row count and checks that table exists
        2. Exit method performs cleanup
        4. Relies on a `Postgres_Connector` class also used as a context manager in order to allow two `Postgres` objects to exist and use the same connection
    4. `Postgres.verify_count()` methods removed because INSERT ON CONFLICT DO UPDATE does not track updated vs. inserted rows, so the only way to do a verify count would be with a JOIN count beforehand
    5. Methods and attributes split into relevant sub-files in order to facilitate edits and coding

### CODE REVIEW

**Comment by jrmidkiff** [comment]
Ready for review and merging

**Comment by floptical** [comment]
@jrmidkiff looking at this just now and I'm confused by your message about removing postgres.verify_count() ? Are you saying the count will be wrong before we commit the transaction?

**Comment by jrmidkiff** [comment]
The `verify_count()` method was a not fully developed method that was made to use with the typical `extract()` to verify that the extracted CSV contained the same number of entries as the table. When doing an `upsert` via the SQL
``` 
INSERT INTO ...
VALUES ...
ON CONFLICT DO 
UPDATE ...
SET ...
```
then the database engine can only say how many rows were either added or updated. So we have no idea how many rows would remain in the table afterwards. Thus the `verify_count()` function would be useless without doing preliminary joins to determine how many of the new rows would represent updates vs inserts

**Comment by floptical** [comment]
> The `verify_count()` method was a not fully developed method that was made to use with the typical `extract()` to verify that the extracted CSV contained the same number of entries as the table. When doing an `upsert` via the SQL
> 
> ```
> INSERT INTO ...
> VALUES ...
> ON CONFLICT DO 
> UPDATE ...
> SET ...
> ```
> 
> then the database engine can only say how many rows were either added or updated. So we have no idea how many rows would remain in the table afterwards. Thus the `verify_count()` function would be useless without doing preliminary joins to determine how many of the new rows would represent updates vs inserts

Oh you meant for an upsert, I get that in the context of an upsert, but we're still going to be using that method when we perform a full truncate and append on the table? Or are we supposed to only be doing upserts going forward?

Currently databridge-airflow-v2 is using the postgres load() method which uses the verify_count() method:

https://github.com/CityOfPhiladelphia/databridge-etl-tools/blob/master/databridge_etl_tools/postgres.py#L487C20-L487C20

**Comment by jrmidkiff** [comment]
Sure, but `verify_count()` assumed that we only use the `load()` method on a (truncated) table with zero rows; I assume that this would not always be the case, that sometimes we want to effectively just append a csv

**Pull request merged**
